name: Build

on:
  push:

jobs:
  docker:
    name: Docker Build + Push
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag:
          - 3.11-jammy
          - 3.11-jammy-apt

    env:
      PUBLIC_IMAGE_PREFIX: 'datastewardshipwizard'
      IMAGE_BASE_NAME: 'python-base'
      DOCKER_META_CONTEXT: '.'
      DOCKER_META_FILE: './${{ matrix.tag }}/Dockerfile'
      DOCKER_META_PLATFORMS: 'linux/amd64,linux/arm64'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    # TEST DOCKER IMAGE BUILD
    - name: Docker meta [test]
      id: meta-test
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.PUBLIC_IMAGE_PREFIX }}/${{ env.IMAGE_BASE_NAME }}
        tags: |
          type=raw,value=${{ matrix.tag }}

    - name: Docker build+push [test]
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKER_META_CONTEXT }}
        file: ${{ env.DOCKER_META_FILE }}
        platforms: ${{ env.DOCKER_META_PLATFORMS }}
        push: false
        tags: ${{ steps.meta-test.outputs.tags }}
        labels: ${{ steps.meta-test.outputs.labels }}

    # PUBLIC: DOCKER HUB
    - name: Docker login [public]
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Docker meta [public]
      id: meta-public
      if: github.event_name != 'pull_request'
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.PUBLIC_IMAGE_PREFIX }}/${{ env.IMAGE_BASE_NAME }}
        tags: |
          type=raw,value=${{ matrix.tag }}

    - name: Docker build+push [public]
      uses: docker/build-push-action@v3
      if: github.event_name != 'pull_request' && steps.meta-public.outputs.tags != ''
      with:
        context: ${{ env.DOCKER_META_CONTEXT }}
        file: ${{ env.DOCKER_META_FILE }}
        platforms: ${{ env.DOCKER_META_PLATFORMS }}
        push: true
        tags: ${{ steps.meta-public.outputs.tags }}
        labels: ${{ steps.meta-public.outputs.labels }}
